# Generated by Django 4.0.1 on 2022-06-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeakerOld',
        ),
        migrations.AlterModelOptions(
            name='speaker',
            options={'verbose_name': 'palestrante', 'verbose_name_plural': 'palestrantes'},
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='created_at',
        ),
    ]
