# Generated by Django 4.0.1 on 2022-06-26 00:45

from django.db import migrations


class Migration(migrations.Migration):
    atomic: False
    dependencies = [
        ('core', '0003_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseOld',
        ),
    ]
