# Generated by Django 4.0.1 on 2022-06-26 00:53

from django.db import migrations


def copy_src_to_dst(Source, Destination):
    for src in Source.objects.all():
        dst = Destination(
            title = src.title,
            start = src.start,
            description = src.description,
            slots = src.slots
        )
        dst.save()

        #associar os speaker a esse Course
        dst.speakers.set(src.speakers.all())

        src.delete()
        

def forward_course_abc_to_mti(apps, schema_editor):
    """
    Para cada ABC, instanciar um MTI com todos os atributos.
    Salvar o MTI
    Associar os speakers do course abc no mti
    E depois deletar o ABC.
    """

    #carregar os modelos.

    CourseAbc = apps.get_model('core', 'CourseOld')
    CourseMti = apps.get_model('core', 'Course')
    copy_src_to_dst(CourseAbc, CourseMti)

def backward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'Course'), 
        apps.get_model('core', 'CourseOld')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti, forward_course_abc_to_mti )
    ]
