# Generated by Django 4.0.1 on 2022-06-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
